# Generated by Django 3.0.5 on 2020-04-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CentroSalud',
            fields=[
                ('id_centro', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'centro_salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_componente', models.CharField(max_length=100)),
                ('medida_componente', models.BigIntegerField()),
            ],
            options={
                'db_table': 'componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregaMedicamento',
            fields=[
                ('id_entrega', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateField()),
                ('cantidad', models.BigIntegerField()),
            ],
            options={
                'db_table': 'entrega_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('fabricante', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedidaComponente',
            fields=[
                ('id_medida', models.BigIntegerField(primary_key=True, serialize=False)),
                ('medida', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'medida_componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rut', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('telefono', models.BigIntegerField()),
                ('correo_electronico', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_receta', models.DateField()),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroInformes',
            fields=[
                ('id_informe', models.FloatField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('informe', models.BinaryField()),
            ],
            options={
                'db_table': 'registro_informes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaMedicamento',
            fields=[
                ('id_reserva', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reserva_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCentroSalud',
            fields=[
                ('id_tipo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_centro', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_centro_salud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id_tipo_componente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_comp', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_componente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id_tipo_empleado', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_empleado', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoInforme',
            fields=[
                ('id_tipo_inf', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_inf', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_informe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMedicamento',
            fields=[
                ('id_tipo_med', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_tipo_med', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTratamiento',
            fields=[
                ('id_tipo_tratamiento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_tratamiento', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_tratamiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='autofarmapage.Persona')),
                ('habilitado', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateField(blank=True, null=True)),
                ('admin', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColaboradorFarmacia',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='autofarmapage.Persona')),
            ],
            options={
                'db_table': 'colaborador_farmacia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('posologia', models.CharField(max_length=250)),
                ('duracion_tratamiento', models.BigIntegerField(blank=True, null=True)),
                ('dosis_diaria', models.BigIntegerField(blank=True, null=True)),
                ('codigo', models.OneToOneField(db_column='codigo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='autofarmapage.Medicamento')),
            ],
            options={
                'db_table': 'detalle_receta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='autofarmapage.Persona')),
            ],
            options={
                'db_table': 'medico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockMedicamento',
            fields=[
                ('stock', models.BigIntegerField()),
                ('id_centro', models.OneToOneField(db_column='id_centro', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='autofarmapage.CentroSalud')),
            ],
            options={
                'db_table': 'stock_medicamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorPaciente',
            fields=[
                ('rut', models.OneToOneField(db_column='rut', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='autofarmapage.Persona')),
            ],
            options={
                'db_table': 'tutor_paciente',
                'managed': False,
            },
        ),
    ]
